### ISSUE TITLE
Ensure schema is in agreement after every migration

### ISSUE THREAD

**Issue by adamdougal** [sky-uk/cqlmigrate#11]
As shown on this page:

https://datastax.github.io/java-driver/2.1.8/features/metadata/

It is possible for a schema changing query to return successfully even if it timed out. This causes an issue when one query alters the schema and the next query to be run requires that schema change. To ensure this doesn't happen we should check after every query that the schema is in agreement and fail if not.

**Comment by jsravn** [comment]
I'm not sure this will improve things. Can't the metadata retrieved in the drive be wrong or stale as well? How often does the driver refresh it, etc.?

Closing, reopen if you guys think this is really necessary.
