### ISSUE TITLE
Set differing read and write consistency levels

### ISSUE THREAD

**Issue by kevinpotgieter** [sky-uk/cqlmigrate#23]
Currently in 0.9.0, the consistency level is defaulted to ALL for both reads and writes when performing migrations. Enforcing ConsistencyLevel.ALL for both might be a little stringent, and has been known to cause read timeouts when attempting to read the schema_updates table when looking to see which files have already been applied. Allowing the user to define what they want as the read/write consistency level would allow more flexibility.

**Comment by jsravn** [comment]
Agreed, ALL/ALL is unnecessary. We need write level + read level > replicas, ALL/ALL is overkill and prone to failure.

**Comment by oliverlockwood** [comment]
Renamed the headline of this issue as the agreed solution is to set different consistency levels for read and write, but not to allow them to be user-configured.
