### ISSUE TITLE
Allow user to specify CL for read/writes

### ISSUE THREAD

**Issue by kevinpotgieter** [sky-uk/cqlmigrate#33]
When running CqlMigrate, allow the user to provide configuration to allow them to override the consistency levels for reads and writes to whatever they deem to be appropriate for their context. Currently the CL defaults are LOCAL_ONE and ALL for reads and writes respectively.

**Comment by chbatey** [comment]
which queries are you thinking about? I assume most queries people manage with cqlmigrate will be schema altering ones that pay no attention to consistency

**Comment by kevinpotgieter** [comment]
I was thinking more along the lines of addressing the inserts into the `schema_updates` table which probably doesn't require ALL, and allowing the user to specify EACH_QUORUM for writes and LOCAL_QUORUM for reads still achieves the same result, but without requiring the high availability of all the nodes. Of course this could be applied to not only the `schema_updates` table, but for any other non-DDL changes you execute as part of your migration.

**Comment by kevinpotgieter** [comment]
FYI - I believe this has already been included as part of [0.9.4](https://github.com/sky-uk/cqlmigrate/releases/tag/0.9.4) release

**Comment by adamdougal** [comment]
Fixed by https://github.com/sky-uk/cqlmigrate/pull/34
