### ISSUE TITLE
Locking

### ISSUE THREAD

**Issue by JacobJohansen** [sky-uk/cqlmigrate#58]
Is there currently a way of using this tool without locking? I would like to use it with scylla db, but scylla does not currently allow for LWT. If not, I can work on adding a configuration to allow for use without locking.

**Comment by adamdougal** [comment]
@JacobJohansen Unfortunately not! However please feel free to submit a PR for it :) 

I think either by being able to disable it all together or by allowing you to set the locking mechanism instead of it being hard coded (and then having a noop locking mechanism) would both be good implementations.

**Comment by JacobJohansen** [comment]
No-op locking was added and merged in, closing issue
