### ISSUE TITLE
How can we increase the wait time in case of lock scenario

### ISSUE THREAD

**Issue by cgoel123** [sky-uk/cqlmigrate#63]
There is an internal locking mechanism which enables multiple application make changes to the same database  on one on one basis so that they do not step on each others feet.
What is the waiting timeout duration currently set in the tool ?
How can we increase this duration ?

**Comment by adamdougal** [comment]
@cgoel123 It defaults to 1 minute: 
https://github.com/sky-uk/cqlmigrate/blob/master/src/main/java/uk/sky/cqlmigrate/LockConfig.java#L70

Please see the README for how to override this value:
https://github.com/sky-uk/cqlmigrate#library-usage
