### ISSUE TITLE
Standalone usage

### ISSUE THREAD

**Issue by hleb-albau** [sky-uk/cqlmigrate#64]
Hi,

Is it possible to use clqmigrate 0.9.6 version jar as standalone app like [here](https://github.com/sky-uk/cqlmigrate#standalone-usage) I just realized, that it doesn't contains dependencies.

**Comment by adamdougal** [comment]
@hleb-albau Thanks for pointing this out. You can now find a jar `with-dependencies` uploaded from version `0.9.8`. 

https://bintray.com/sky-uk/oss-maven/cqlmigrate/0.9.8#files/uk%2Fsky%2Fcqlmigrate%2F0.9.8
