### ISSUE TITLE
Release 0.9.7 (key-space locking).

### ISSUE THREAD

**Issue by chyzwar** [sky-uk/cqlmigrate#65]
Hi, 

I can see some changes in master that include No op locking. 
It is possible to release new version of cqlmigrate that include these?

Thanks

**Comment by charlie-mcneill** [comment]
0.9.7 Released :)

**Comment by chyzwar** [comment]
Thank you ;)

2017-09-22 18:06 GMT+01:00 Charlie McNeill <notifications@github.com>:
