### ISSUE TITLE
Migrate away from Bintray

### ISSUE THREAD

**Issue by adamdougal** [sky-uk/cqlmigrate#94]
We currenty upload the `cqlmigrate` artefacts to Bintray. Unfortunately, it's being shut down so we need to find an alternative solution. https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by oliverlockwood** [comment]
FYI @adamdougal I just did the same change for a Java library (built using Maven though) which I'm involved in maintaining.  If it's useful to you, feel free to inspect the commit at https://github.com/dalet-oss/vfs-gcs/commit/035f62d90697cb1ed53da151e607f138c9d1a88e.  

Obviously you'll still need to:
- register a user account with Sonatype
- make sure that user has access to the artifact group ID (as this is currently `uk.sky`, you might get asked to create a specifically-named file on the sky.uk website; it might be easier to change the artifact group ID to `com.github.sky-uk` as then all you have to do is create a specifically-named repo)
- set up the relevant secrets in Travis config if you want to do like us and get Travis to perform the artifact publication to Maven Central.

**Comment by adamdougal** [comment]
Hey @oliverlockwood 👋  Hope you're keeping well! Thanks for the tips and example, that's a great help! Hopefully I'll be able to look at this in the next couple of weeks.

**Comment by adamdougal** [comment]
Raised a Jira ticket to claim the `uk.sky` group https://issues.sonatype.org/browse/OSSRH-68108

**Comment by adamdougal** [comment]
They've requested that we make a text file referencing that issue available on the `sky.uk` domain. I've emailed the Sky domain team to see if this is possible.

**Comment by adamdougal** [comment]
CqlMigrate is now available via Maven Central https://search.maven.org/artifact/uk.sky/cqlmigrate

I've backported the following versions:
- `0.10.3`
- `0.11.0`
- `0.12.0`
